<a href="https://colab.research.google.com/github/SyedaTabinda804/fictional_t/blob/main/MLcourse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Examples**

example 1:


In [ ]:
print ("Name: Ali")

Name: Ali



example 2:


In [ ]:
var0= 0
var1= "Hello Python"
var2= 32
var3= 56.4
print("var0:",type(var0))
print("var1:",type(var1))
print("var1:",type(var2))
print("var1:",type(var3))

var0: <class 'int'>
var1: <class 'str'>
var1: <class 'int'>
var1: <class 'float'>



example 3:


In [ ]:
def add(a,b):
   c = int(a) + int(b)
   print(" Add result:" ,c)

if __name__ == "__main__":
   print("Enter First Number:")
   a = input()
   print("Enter Second Number:")
   b = input()
   add(a,b)


Enter First Number:
25
Enter Second Number:
5
 Add result: 30



Example 4


In [ ]:
def add(a, b):
  c = int (a) + int(b)
  print(" ADD result: " ,c)

add ( 2, 3)

 ADD result:  5



Question:

solve these examples:

1.
Write a program which can perform ADD, Subtract, Multiply and Divide
operations with the help of Functions. Multiply Function should be parametrized
function and other functions should be default functions.


In [ ]:
def add():
    a = input("Enter the first number: ")
    b = input("Enter the second number: ")
    try:
        c = int(a) + int(b)
        print("Add result:", c)
    except ValueError:
        print("Invalid input. Please enter numbers only.")

def subtract():
    a = input("Enter the first number: ")
    b = input("Enter the second number: ")
    try:
        c = int(a) - int(b)
        print("Subtract result:", c)
    except ValueError:
        print("Invalid input. Please enter numbers only.")

def divide():
    a = input("Enter the first number: ")
    b = input("Enter the second number: ")
    try:
        if int(b) == 0:
            print("Cannot divide by zero.")
        else:
            c = int(a) / int(b)
            print("Divide result:", c)
    except ValueError:
        print("Invalid input. Please enter numbers only.")
    except ZeroDivisionError:
        print("Cannot divide by zero.")


def multiply(a, b):
    try:
        c = int(a) * int(b)
        print("Multiply result:", c)
    except ValueError:
        print("Invalid input. Please enter numbers only.")


if __name__ == "__main__":
    while True:
        print("\nSelect operation:")
        print("1. Add")
        print("2. Subtract")
        print("3. Multiply")
        print("4. Divide")
        print("5. Exit")

        choice = input("Enter choice(1/2/3/4/5): ")

        if choice == '1':
            add()
        elif choice == '2':
            subtract()
        elif choice == '3':
            a = input("Enter the first number: ")
            b = input("Enter the second number: ")
            multiply(a, b)
        elif choice == '4':
            divide()
        elif choice == '5':
            break
        else:
            print("Invalid Input")


Select operation:
1. Add
2. Subtract
3. Multiply
4. Divide
5. Exit
Enter choice(1/2/3/4/5): 1
Enter the first number: 512
Enter the second number: 12
Add result: 524

Select operation:
1. Add
2. Subtract
3. Multiply
4. Divide
5. Exit
Enter choice(1/2/3/4/5): 5


Question:

solve these examples:

2.
Write a python program which get two inputs from the user and calculate the
average of these numbers. The average function should be implemented as a
function.

In [ ]:
def calculate_average(num1, num2):
    try:
        num1 = float(num1)
        num2 = float(num2)
        average = (num1 + num2) / 2
        return average
    except ValueError:
        print("Invalid input. Please enter numbers only.")
        return None

if __name__ == "__main__":
    num1 = input("Enter the first number: ")
    num2 = input("Enter the second number: ")

    average = calculate_average(num1, num2)
    if average is not None:
      print("The average of", num1, "and", num2, "is ", average)

Enter the first number: 25
Enter the second number: 5
The average of 25 and 5 is  15.0


In [ ]:
def is_right_triangle(a, b, c):
    sides = sorted([a, b, c])
    if sides[0]**2 + sides[1]**2 == sides[2]**2:
        return True
    else:
        return False

# Get input from the user
side1 = float(input("Enter the length of the first side: "))
side2 = float(input("Enter the length of the second side: "))
side3 = float(input("Enter the length of the third side: "))

# Check if it's a right-angled triangle
if is_right_triangle(side1, side2, side3):
    print("The triangle is a right-angled triangle.")
else:
    print("The triangle is not a right-angled triangle.")

**LAB no 2**

In [3]:
# prompt: Given string contains a combination of the lower and upper case letters. Write a
# program to arrange the characters of a string so that all lowercase letters should
# come first.    string: "ProGrAmMer" . note: show output

def arrange_string(input_string):
    lower_case_chars = ""
    upper_case_chars = ""
    for char in input_string:
        if 'a' <= char <= 'z':
            lower_case_chars += char
        else:
            upper_case_chars += char
    return lower_case_chars + upper_case_chars

input_string = "ProGrAmMer"
result = arrange_string(input_string)
print(result)  # Output: oarmrPGMer

rormerPGAM


In [4]:
# prompt: Write a python program to print the inverse tuple.

def inverse_tuple(input_tuple):
    """Inverts a tuple.

    Args:
      input_tuple: The tuple to invert.

    Returns:
      The inverted tuple.
    """
    return tuple(reversed(input_tuple))

# Example usage
my_tuple = (1, 2, 3, 4, 5)
inverted_tuple = inverse_tuple(my_tuple)
print(inverted_tuple)  # Output: (5, 4, 3, 2, 1)

(5, 4, 3, 2, 1)


In [5]:
# prompt: Write a python program to swap the two tuples.

def swap_tuples(tuple1, tuple2):
    """Swaps two tuples.

    Args:
      tuple1: The first tuple.
      tuple2: The second tuple.

    Returns:
      A tuple containing the swapped tuples.
    """
    return tuple2, tuple1

# Example usage
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)

tuple1, tuple2 = swap_tuples(tuple1, tuple2)

print("Tuple 1 after swapping:", tuple1)
print("Tuple 2 after swapping:", tuple2)

Tuple 1 after swapping: (4, 5, 6)
Tuple 2 after swapping: (1, 2, 3)


In [6]:
# prompt: Get the key of a minimum and maximum value from the following dictionary. The
# dictionary is given below.

def find_min_max_keys(input_dict):
    if not input_dict:
        return {}, {}
    min_value = min(input_dict.values())
    max_value = max(input_dict.values())

    min_keys = {key for key, value in input_dict.items() if value == min_value}
    max_keys = {key for key, value in input_dict.items() if value == max_value}
    return min_keys, max_keys
my_dict = {"C++": 82, "Machine Learning": 65, "OOP": 75, "PF": 63, "DSA": 79}
min_key, max_key = find_min_max_keys(my_dict)
print("Keys with minimum value:", min_key)
print("Keys with maximum value:", max_key)

Keys with minimum value: {'PF'}
Keys with maximum value: {'C++'}


In [7]:
# prompt: Write a Python program to return a new set with unique items from both sets by removing duplicates.

def unique_items_from_sets(set1, set2):
    """
    Returns a new set with unique items from both sets by removing duplicates.

    Args:
        set1: The first set.
        set2: The second set.

    Returns:
        A new set containing unique items from both input sets.
    """
    return set1.union(set2)

# Example usage
set1 = {1, 2, 3, 4, 5}
set2 = {3, 5, 6, 7, 8}

unique_set = unique_items_from_sets(set1, set2)
print(unique_set)  # Output: {1, 2, 3, 4, 5, 6, 7, 8}

{1, 2, 3, 4, 5, 6, 7, 8}


In [8]:
# prompt: Check if two sets have any elements in common. If yes, display the common elements

def check_common_elements(set1, set2):
    """
    Checks if two sets have any elements in common. If yes, displays the common elements.

    Args:
        set1: The first set.
        set2: The second set.
    """
    common_elements = set1.intersection(set2)
    if common_elements:
        print("Common elements:", common_elements)
    else:
        print("No common elements found.")

# Example usage
set1 = {1, 2, 3, 4, 5}
set2 = {3, 5, 6, 7, 8}
check_common_elements(set1, set2)  # Output: Common elements: {3, 5}


set3 = {1, 2}
set4 = {6, 7}
check_common_elements(set3, set4) # Output: No common elements found.

Common elements: {3, 5}
No common elements found.


In [9]:
# prompt: Write a python program to get string from the user and print the 2:7 index elements with slicing.

def get_string_slice():
    input_string = input("Enter a string: ")
    sliced_string = input_string[2:7]
    print("Sliced string (index 2 to 7):", sliced_string)

if __name__ == "__main__":
    get_string_slice()

Enter a string: I'm just a girl !!!
Sliced string (index 2 to 7): m jus


In [10]:
# prompt: Write a python program to create 2D numpy array and convert into 1D flatten array.

import numpy as np

# Create a 2D NumPy array
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Convert the 2D array to a 1D flattened array
one_d_array = two_d_array.flatten()

# Print the original 2D array
print("Original 2D array:")
print(two_d_array)

# Print the flattened 1D array
print("\nFlattened 1D array:")
one_d_array

Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened 1D array:


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# prompt: Write a python program to create Zeros array and Ones array.

import numpy as np

# Create a zeros array of shape (3, 4)
zeros_array = np.zeros((3, 4))
print("Zeros array:\n", zeros_array)

# Create an ones array of shape (2, 2)
ones_array = np.ones((2, 2))
print("\nOnes array:\n", ones_array)

Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array:
 [[1. 1.]
 [1. 1.]]


In [12]:
# prompt: Write a python program to find the most frequent value in a NumPy array.

import numpy as np

def most_frequent_value(arr):
    """
    Finds the most frequent value in a NumPy array.

    Args:
    arr: A NumPy array.

    Returns:
    The most frequent value in the array, or None if the array is empty.
    """
    if arr.size == 0:
        return None

    values, counts = np.unique(arr, return_counts=True)
    index = np.argmax(counts)
    return values[index]

# Example usage
my_array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
most_frequent = most_frequent_value(my_array)
print(f"The most frequent value in the array is: {most_frequent}")

my_array = np.array([])
most_frequent = most_frequent_value(my_array)
print(f"The most frequent value in the array is: {most_frequent}")

The most frequent value in the array is: 4
The most frequent value in the array is: None


In [13]:
# prompt: Create two numpy arrays and perform
# a) Sum
# b) Subtraction
# c) Multiplication
# d) Division
# e) Concatenation

import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# a) Sum
sum_array = array1 + array2
print("Sum:", sum_array)

# b) Subtraction
sub_array = array1 - array2
print("Subtraction:", sub_array)

# c) Multiplication
mul_array = array1 * array2
print("Multiplication:", mul_array)

# d) Division
div_array = array1 / array2
print("Division:", div_array)

# e) Concatenation
concat_array = np.concatenate((array1, array2))
print("Concatenation:", concat_array)

Sum: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Concatenation: [ 1  2  3  4  5  6  7  8  9 10]



Example no 1

In [14]:
a='AIMAL';
print(a)

AIMAL



Example no 2

In [16]:
for x in a:
  print(x)

A
I
M
A
L



Example no 3


In [17]:
str = "Start from python";
print(str[1:6])

tart 



Example no 4


In [18]:
stdname=["Ali", "Hassan", "Hamza", "Attique"]
print(stdname)
print(type(stdname))

['Ali', 'Hassan', 'Hamza', 'Attique']
<class 'list'>



Example no 5


In [19]:
stdname=["Ali", "Hassan", "Hamza"]
for i in range(len(stdname)):
  print(stdname[i])

Ali
Hassan
Hamza



Example no 6


In [2]:
stdname=["Ali", "Hassan", "Hamza"]
i=0
while i < len(stdname):
  print(stdname[i])
  i = i+1

Ali
Hassan
Hamza



Example no 7


In [3]:
courses = ("AI", "DS", "ML")
print(courses)

('AI', 'DS', 'ML')



Example no 8


In [4]:
courses = ("AI", "DS", "ML")
for i in range(len(courses)):
  print(courses[i])

AI
DS
ML



Example no 9


In [5]:
sets = {"AI", "DS", "ML"}
print(sets)

{'ML', 'DS', 'AI'}



Example no 10


In [7]:
sets = {"AI", "DS", "ML"}
for i in range(len(sets)):
  print(i)

0
1
2



Example no 11


In [9]:
student = {"name": "Ali",
           "age": 20,
           "course": "AI"}
print(student)

{'name': 'Ali', 'age': 20, 'course': 'AI'}



Example no 12


In [10]:
for i in student:
  print(i)

name
age
course



Example no 13


In [11]:
for i in student:
  print(student[i])

Ali
20
AI



Example no 14


In [12]:
for i, j in student.items():
  print(i,j)

name Ali
age 20
course AI



Example no 15


In [13]:
import numpy as np
print(np.__version__)

1.26.4



Example no 15


In [14]:
arr1d=np.array([1,2,3,4])
print(arr1d)

[1 2 3 4]



Example no 16


In [15]:
arr2d=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2d)

[[1 2 3 4]
 [5 6 7 8]]



Example no 17


In [16]:
arr7d = np.array([1, 2, 3, 4], ndmin=7)
print(arr7d)
print(arr7d.ndim)

[[[[[[[1 2 3 4]]]]]]]
7



Example no 18


In [17]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)



Example no 19


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,12,33,98,77])
newarr = arr.reshape(4, 4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [12 33 98 77]]



Example no 20


In [19]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]



Example no 21


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 2)


Example no 22


In [22]:
a1=np.array([[1,2,3,4]])
print("Size of Array: ", a1.shape)
print("Memory utilizing to store: ", a1.nbytes)
print("Sum: ",a1.sum())
print("Max value from the array: ",a1.max())
print("Min value from the array: ", a1.min())
print("Mean Value: ",a1.mean())

Size of Array:  (1, 4)
Memory utilizing to store:  32
Sum:  10
Max value from the array:  4
Min value from the array:  1
Mean Value:  2.5
